version: '3.7'
services:
    mysql-ktvtpm-lab4-container:
        image: mysql:8.0.28
        container_name: mysql-ktvtpm-lab4-container
        volumes:
            # tạo volumes
            - mysql-ktvtkpm-lab4-data:/var/lib/mysql
            - mysql-ktvtkpm-lab4-config-deamond:/etc/mysql/conf.d
            # tạo database
            - ".qlchuyenbay/./db:/var/lib/mysql"
        ports:
            - 12000:3306
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: qlchuyenbay
        networks:
            - ktvtpm-lab4-network

    java-ktvtpm-lab4-container:
        build: .
        image: ktvtkpm-lab4:v1.0.0
        container_name: java-ktvtpm-lab4-container
        ports:
            - 13000:13000
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql-ktvtpm-lab4-container
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE_NAME: qlchuyenbay
        networks:
            - ktvtpm-lab4-network

networks:
    ktvtpm-lab4-network:
        name: ktvtpm-lab4-network

volumes:
    mysql-ktvtkpm-lab4-data:
    mysql-ktvtkpm-lab4-config-deamond:
